swagger: "2.0"
info:
  description: This is the REST API providing for the Szeretetfoldje daily message app
  title: Szeretetfoldje daily message API
  version: 0.1.0
schemes:
- http
- https
basePath: /api
consumes:
  - application/keyauth.api.v1+json
produces:
  - application/keyauth.api.v1+json
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: x-token
security:
  - key: []
paths:
  /:
    get:
      tags:
        - daily
      operationId: getDaily
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
      responses:
        200:
          description: list of daily items since given id
          schema:
            type: array
            items:
              $ref: "#/definitions/daily"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - daily
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/daily"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/daily"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags:
        - daily
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/daily"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/daily"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - daily
      operationId: destroyOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  daily:
    type: object
    required:
      - message
      - verse
      - pray
      - title
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      message:
        type: string
        minLength: 1
      verse:
        type: string
        minLength: 1
      pray:
        type: string
        minLength: 1
      title:
        type: string
        minLength: 1
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  principal:
    type: string
