// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Szeretetfoldje daily message API
This is the REST API providing for the Szeretetfoldje daily message app


    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
